// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PointOfSale.Data.DBContext;

#nullable disable

namespace PointOfSale.Data.Migrations
{
    [DbContext(typeof(POINTOFSALEContext))]
    [Migration("20260211101607_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PointOfSale.Model.Category", b =>
                {
                    b.Property<int>("IdCategory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idCategory");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCategory"));

                    b.Property<string>("Description")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("description");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isActive");

                    b.Property<DateTime?>("RegistrationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("registrationDate")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("IdCategory")
                        .HasName("PK__Category__79D361B6930E16FF");

                    b.ToTable("Category", (string)null);
                });

            modelBuilder.Entity("PointOfSale.Model.CorrelativeNumber", b =>
                {
                    b.Property<int>("IdCorrelativeNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idCorrelativeNumber");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCorrelativeNumber"));

                    b.Property<DateTime?>("DateUpdate")
                        .HasColumnType("timestamp")
                        .HasColumnName("dateUpdate");

                    b.Property<int?>("LastNumber")
                        .HasColumnType("integer")
                        .HasColumnName("lastNumber");

                    b.Property<string>("Management")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("management");

                    b.Property<int?>("QuantityDigits")
                        .HasColumnType("integer")
                        .HasColumnName("quantityDigits");

                    b.HasKey("IdCorrelativeNumber")
                        .HasName("PK__Correlat__D71CDFB02EFC51E4");

                    b.ToTable("CorrelativeNumber", (string)null);
                });

            modelBuilder.Entity("PointOfSale.Model.DetailSale", b =>
                {
                    b.Property<int>("IdDetailSale")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idDetailSale");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDetailSale"));

                    b.Property<string>("BrandProduct")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("brandProduct");

                    b.Property<string>("CategoryProducty")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("categoryProducty");

                    b.Property<string>("DescriptionProduct")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("descriptionProduct");

                    b.Property<int?>("IdProduct")
                        .HasColumnType("integer")
                        .HasColumnName("idProduct");

                    b.Property<int?>("IdSale")
                        .HasColumnType("integer")
                        .HasColumnName("idSale");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price");

                    b.Property<int?>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<decimal?>("Total")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("total");

                    b.HasKey("IdDetailSale")
                        .HasName("PK__DetailSa__D072342E21B249E9");

                    b.HasIndex("IdSale");

                    b.ToTable("DetailSale", (string)null);
                });

            modelBuilder.Entity("PointOfSale.Model.Menu", b =>
                {
                    b.Property<int>("IdMenu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idMenu");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMenu"));

                    b.Property<string>("Controller")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("controller");

                    b.Property<string>("Description")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("description");

                    b.Property<string>("Icon")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("icon");

                    b.Property<int?>("IdMenuParent")
                        .HasColumnType("integer")
                        .HasColumnName("idMenuParent");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isActive");

                    b.Property<string>("PageAction")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("pageAction");

                    b.Property<DateTime?>("RegistrationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("registrationDate")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("IdMenu")
                        .HasName("PK__Menu__C26AF48328C80B96");

                    b.HasIndex("IdMenuParent");

                    b.ToTable("Menu", (string)null);
                });

            modelBuilder.Entity("PointOfSale.Model.Negocio", b =>
                {
                    b.Property<int>("IdNegocio")
                        .HasColumnType("integer")
                        .HasColumnName("idNegocio");

                    b.Property<string>("Correo")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("correo");

                    b.Property<string>("Direccion")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("direccion");

                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.Property<string>("NombreLogo")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombreLogo");

                    b.Property<string>("NumeroDocumento")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numeroDocumento");

                    b.Property<decimal?>("PorcentajeImpuesto")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("porcentajeImpuesto");

                    b.Property<string>("SimboloMoneda")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("simboloMoneda");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("telefono");

                    b.Property<string>("UrlLogo")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("urlLogo");

                    b.HasKey("IdNegocio")
                        .HasName("PK__Negocio__70E1E107B97CE30F");

                    b.ToTable("Negocio", (string)null);
                });

            modelBuilder.Entity("PointOfSale.Model.Product", b =>
                {
                    b.Property<int>("IdProduct")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idProduct");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdProduct"));

                    b.Property<string>("BarCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("barCode");

                    b.Property<string>("Brand")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("brand");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("description");

                    b.Property<int?>("IdCategory")
                        .HasColumnType("integer")
                        .HasColumnName("idCategory");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isActive");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("bytea")
                        .HasColumnName("photo");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price");

                    b.Property<int?>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<DateTime?>("RegistrationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("registrationDate")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("IdProduct")
                        .HasName("PK__Product__5EEC79D18F8E118B");

                    b.HasIndex("IdCategory");

                    b.ToTable("Product", (string)null);
                });

            modelBuilder.Entity("PointOfSale.Model.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idRol");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRol"));

                    b.Property<string>("Description")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("description");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isActive");

                    b.Property<DateTime?>("RegistrationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("registrationDate")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("IdRol")
                        .HasName("PK__Rol__3C872F76804F2E15");

                    b.ToTable("Rol", (string)null);
                });

            modelBuilder.Entity("PointOfSale.Model.RolMenu", b =>
                {
                    b.Property<int>("IdRolMenu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idRolMenu");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRolMenu"));

                    b.Property<int?>("IdMenu")
                        .HasColumnType("integer")
                        .HasColumnName("idMenu");

                    b.Property<int?>("IdRol")
                        .HasColumnType("integer")
                        .HasColumnName("idRol");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isActive");

                    b.Property<DateTime?>("RegistrationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("registrationDate")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("IdRolMenu")
                        .HasName("PK__RolMenu__CD2045D86DACA6AF");

                    b.HasIndex("IdMenu");

                    b.HasIndex("IdRol");

                    b.ToTable("RolMenu", (string)null);
                });

            modelBuilder.Entity("PointOfSale.Model.Sale", b =>
                {
                    b.Property<int>("IdSale")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idSale");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdSale"));

                    b.Property<string>("ClientName")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("clientName");

                    b.Property<string>("CustomerDocument")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("customerDocument");

                    b.Property<int?>("IdTypeDocumentSale")
                        .HasColumnType("integer")
                        .HasColumnName("idTypeDocumentSale");

                    b.Property<int?>("IdUsers")
                        .HasColumnType("integer")
                        .HasColumnName("idUsers");

                    b.Property<DateTime?>("RegistrationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("registrationDate")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("SaleNumber")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("saleNumber");

                    b.Property<decimal?>("Subtotal")
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal?>("Total")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("total");

                    b.Property<decimal?>("TotalTaxes")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("totalTaxes");

                    b.HasKey("IdSale")
                        .HasName("PK__Sale__C4AEB198091B7829");

                    b.HasIndex("IdTypeDocumentSale");

                    b.HasIndex("IdUsers");

                    b.ToTable("Sale", (string)null);
                });

            modelBuilder.Entity("PointOfSale.Model.SaleItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("SaleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SaleId");

                    b.ToTable("SaleItems");
                });

            modelBuilder.Entity("PointOfSale.Model.TypeDocumentSale", b =>
                {
                    b.Property<int>("IdTypeDocumentSale")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idTypeDocumentSale");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTypeDocumentSale"));

                    b.Property<string>("Description")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("description");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isActive");

                    b.Property<DateTime?>("RegistrationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("registrationDate")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("IdTypeDocumentSale")
                        .HasName("PK__TypeDocu__18211B893F81F3B8");

                    b.ToTable("TypeDocumentSale", (string)null);
                });

            modelBuilder.Entity("PointOfSale.Model.User", b =>
                {
                    b.Property<int>("IdUsers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idUsers");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUsers"));

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("email");

                    b.Property<int?>("IdRol")
                        .HasColumnType("integer")
                        .HasColumnName("idRol");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isActive");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("password");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("bytea")
                        .HasColumnName("photo");

                    b.Property<DateTime?>("RegistrationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("registrationDate")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("IdUsers")
                        .HasName("PK__Users__981CF2B10C1B1086");

                    b.HasIndex("IdRol");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PointOfSale.Model.DetailSale", b =>
                {
                    b.HasOne("PointOfSale.Model.Sale", "IdSaleNavigation")
                        .WithMany("DetailSales")
                        .HasForeignKey("IdSale")
                        .HasConstraintName("FK__DetailSal__idSal__300424B4");

                    b.Navigation("IdSaleNavigation");
                });

            modelBuilder.Entity("PointOfSale.Model.Menu", b =>
                {
                    b.HasOne("PointOfSale.Model.Menu", "IdMenuParentNavigation")
                        .WithMany("InverseIdMenuParentNavigation")
                        .HasForeignKey("IdMenuParent")
                        .HasConstraintName("FK__Menu__idMenuPare__108B795B");

                    b.Navigation("IdMenuParentNavigation");
                });

            modelBuilder.Entity("PointOfSale.Model.Product", b =>
                {
                    b.HasOne("PointOfSale.Model.Category", "IdCategoryNavigation")
                        .WithMany("Products")
                        .HasForeignKey("IdCategory")
                        .HasConstraintName("FK__Product__idCateg__22AA2996");

                    b.Navigation("IdCategoryNavigation");
                });

            modelBuilder.Entity("PointOfSale.Model.RolMenu", b =>
                {
                    b.HasOne("PointOfSale.Model.Menu", "IdMenuNavigation")
                        .WithMany("RolMenus")
                        .HasForeignKey("IdMenu")
                        .HasConstraintName("FK__RolMenu__idMenu__182C9B23");

                    b.HasOne("PointOfSale.Model.Rol", "IdRolNavigation")
                        .WithMany("RolMenus")
                        .HasForeignKey("IdRol")
                        .HasConstraintName("FK__RolMenu__idRol__173876EA");

                    b.Navigation("IdMenuNavigation");

                    b.Navigation("IdRolNavigation");
                });

            modelBuilder.Entity("PointOfSale.Model.Sale", b =>
                {
                    b.HasOne("PointOfSale.Model.TypeDocumentSale", "IdTypeDocumentSaleNavigation")
                        .WithMany("Sales")
                        .HasForeignKey("IdTypeDocumentSale")
                        .HasConstraintName("FK__Sale__idTypeDocu__2B3F6F97");

                    b.HasOne("PointOfSale.Model.User", "IdUsersNavigation")
                        .WithMany("Sales")
                        .HasForeignKey("IdUsers")
                        .HasConstraintName("FK__Sale__idUsers__2C3393D0");

                    b.Navigation("IdTypeDocumentSaleNavigation");

                    b.Navigation("IdUsersNavigation");
                });

            modelBuilder.Entity("PointOfSale.Model.SaleItem", b =>
                {
                    b.HasOne("PointOfSale.Model.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PointOfSale.Model.Sale", "Sale")
                        .WithMany("SaleItems")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("PointOfSale.Model.User", b =>
                {
                    b.HasOne("PointOfSale.Model.Rol", "IdRolNavigation")
                        .WithMany("Users")
                        .HasForeignKey("IdRol")
                        .HasConstraintName("FK__Users__idRol__1BFD2C07");

                    b.Navigation("IdRolNavigation");
                });

            modelBuilder.Entity("PointOfSale.Model.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("PointOfSale.Model.Menu", b =>
                {
                    b.Navigation("InverseIdMenuParentNavigation");

                    b.Navigation("RolMenus");
                });

            modelBuilder.Entity("PointOfSale.Model.Rol", b =>
                {
                    b.Navigation("RolMenus");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("PointOfSale.Model.Sale", b =>
                {
                    b.Navigation("DetailSales");

                    b.Navigation("SaleItems");
                });

            modelBuilder.Entity("PointOfSale.Model.TypeDocumentSale", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("PointOfSale.Model.User", b =>
                {
                    b.Navigation("Sales");
                });
#pragma warning restore 612, 618
        }
    }
}
